###---NGFW_Policy---###
#(here we assume that user is already created and only the firewall policies are being applied to a specified number of users in the below sets)


    # Creates a dedicated "Sub-chain" for a specific policy (e.g., "Guest_Timed_Access").
    # These don't have hooks yet, so they don't process traffic until 'jumped' to.
    
        nft add chain inet nat <timed_policy_name>
        nft add chain inet filter <timed_policy_name>
    
    # Creates a dynamic list for users belonging to this policy. 
    # Using 'flags interval' allows you to add entire subnets to a policy at once.
    
        nft add set inet nat <user_set_name> '{ type ipv4_addr; flags interval; }'
        nft add set inet filter <user_set_name> '{ type ipv4_addr; flags interval; }'
    
    # If a user is in the set, perform an action (like 'accept' to bypass the portal).
    
        nft add rule inet nat <policy_name> ip saddr @<user_set_name> <action>

    # Destination-specific NAT: e.g., allow them to bypass the portal ONLY for the company website.
    
        nft add rule inet nat <policy_name> ip saddr @<user_set_name> ip daddr <destination_ip> <action>

    # THE EXIT RAMP: If the packet didn't match the specific rules above, 
    # stop looking in this policy and go back to the main NAT chain.
    
        nft add rule inet nat <policy_name> return

    # If a user is in the set, perform an action (like 'accept' to bypass the portal).
    
        nft add rule inet nat <policy_name> ip saddr @<user_set_name> <action>

    # Destination-specific NAT: e.g., allow them to bypass the portal ONLY for the company website.
    
        nft add rule inet nat <policy_name> ip saddr @<user_set_name> ip daddr <destination_ip> <action>

    # THE EXIT RAMP: If the packet didn't match the specific rules above, 
    # stop looking in this policy and go back to the main NAT chain.
    
        nft add rule inet nat <policy_name> return

    # This is the "Trigger." 
    # It tells the firewall: "As soon as a packet arrives from an ip in this set, 
    # check the <policy_name> chain immediately."
    
        nft insert rule inet nat prerouting ip saddr @<user_set_name> jump <policy_name>
        nft insert rule inet filter input ip saddr @<user_set_name> jump <policy_name>