###---vpn connection to be ran on setup server and bootup after server setup---###

    
    # Allows the encrypted VPN tunnel to be established.
    # iifname @wan_ifaces: Traffic coming from the internet.
    # udp dport <port>: Opens the specific 'door' for the VPN (e.g., 51820 for WireGuard or 1194 for OpenVPN).
    # <action>: Usually 'accept'.

        nft add rule inet filter input iifname @wan_ifaces udp dport <vpn_server_port> <action>

    # Handling OUTBOUND traffic from the VPN user.
    # 'insert rule': Places this at the TOP of the chain to ensure it bypasses later 'drop' rules.
    # iifname <vpn_iface>: Traffic coming FROM the VPN tunnel.
    # <action>: Usually 'accept' to let VPN users reach the LAN or Internet.

        nft add rule inet filter forward iifname <vpn_iface> <action>

    # Handling INBOUND traffic back to the VPN user.
    # oifname <vpn_iface>: Traffic leaving the router GOING TO the VPN tunnel.
    # This ensures that data requested by the VPN user can actually be sent back to them.

        nft add rule inet filter forward oifname <vpn_iface> <action>