###---DMZ---###

######For Either TCP or UDP or both protocols, incase of both protocols the rules are applied twice once for UDP once for TCP######

    # 1. ALLOW INTERNET ACCESS
    # Adds the client to the global whitelist so the router allows their general outgoing traffic.

        nft add element inet filter allowed_ip4 { <client_ip> }

    # 2. UPLOAD TRAFFIC MARKING (Internal -> External)
    # Specifically tags traffic originating from a local IP and Port.
    # This sets marks to the data being sent OUT from your server for the ISP/QoS.

        nft add rule inet mangle prerouting ip saddr <client_ip> <protocol> sport <client_port> meta mark set 0x00<isp_mark><tc_class_marks>

    # 3. DOWNLOAD TRAFFIC MARKING (External -> Internal)
    # Specifically tags traffic destined FOR your local server.
    # This allows the router to manage the bandwidth of incoming requests so they don't choke the network.

        nft add rule inet mangle forward ip daddr <client_ip> <protocol> dport <client_port> meta mark set 0x00<isp_mark><tc_class_marks>

    # 4. THE PORT FORWARD (DNAT)
    # 'insert rule' puts this at the TOP of the NAT chain.
    # It takes traffic hitting your Public WAN IP on a specific port and "NATs" (steers) it to the local Private IP.

        nft insert rule inet nat NAT_PRE ip daddr <public_facing_isp_ip> <protocol> dport <client_port> dnat to <client_ip>:<client_port>

    # 5. THE SECURITY PERMIT
    # Because your 'forward' chain policy is set to 'drop', you must explicitly allow the incoming 
    # packets to pass through the filter after they have been translated by the NAT rule above.

        nft insert rule inet filter FILTER_FORWARD ip daddr <client_ip> <action>

######For all the traffic coming in to the the public facing ip will be redirected to the clients ips######    

    # 1. THE PERMIT: Allows the internal client to send traffic OUT to the internet.
    # Without this, the client can receive data but cannot 'reply' back.
    
        nft add element inet filter allowed_ip4 { <client_ip> }

    # 2. THE QOS MARKER: Labels the client's traffic for bandwidth management.
    # This ensures that even forwarded traffic respects the user's Speed Limit (TC Class).

        nft add element inet mangle user4_marks { <client_ip> : 0x00<isp_mark><tc_class_marks> }

    # 3. THE TRANSLATOR (DNAT): The 'Destination NAT' rule.
    # Whenever a packet hits your Public ISP IP, this rule "rewrites" the 
    # destination address to the Client's Private IP before it's routed.
    
        nft insert rule inet nat NAT_PRE ip daddr <public_facing_isp_ip> dnat to <client_ip>

    # 4. THE GATEKEEPER: Specifically allows traffic THROUGH the 'Forward' chain.
    # Since your main policy is 'drop', you must explicitly allow packets heading 
    # to the <client_ip>. The <action> is typically 'accept'.

        nft insert rule inet filter FILTER_FORWARD ip daddr <client_ip> <action>

