#Selective Port Forwarding

nft add element inet filter allowed_ip4 { <client_ip> }
nft add rule inet mangle prerouting \
    ip saddr <client_ip> <protocol> sport <client_port> \
    meta mark set 0x00<isp_mark><tc_class_marks>
nft add rule inet mangle forward \
    ip daddr <client_ip> <protocol> dport <client_port> \
    meta mark set 0x00<isp_mark><tc_class_marks>
nft insert rule inet nat NAT_PRE \
    ip daddr <public_facing_isp_ip> <protocol> dport <public_facing_isp_port> \
    dnat to <client_ip>:<client_port>
nft insert rule inet filter FILTER_FORWARD ip daddr <client_ip> <action>

#Selective Port Pool Forwarding

nft add element inet filter allowed_ip4 { <client_ip> }
nft add rule inet mangle prerouting \
    ip saddr <client_ip> <protocol> sport <starting_client_port>-<ending_client_port> \
    meta mark set 0x00<isp_mark><tc_class_marks>
nft add rule inet mangle forward \
    ip daddr <client_ip> <protocol> dport <starting_client_port>-<ending_client_port> \
    meta mark set 0x00<isp_mark><tc_class_marks>
nft insert rule inet nat NAT_PRE \
    ip daddr <public_facing_isp_ip> <protocol> dport <starting_public_facing_isp_port>-<ending_public_facing_isp_port> \
    dnat to <client_ip>:<starting_client_port>-<ending_client_port>
nft insert rule inet filter FILTER_FORWARD ip daddr <client_ip> <action>

#Full DMZ All Incoming Traffic → Single Host

nft add element inet filter allowed_ip4 { <client_ip> }
nft add element inet mangle user4_marks { <client_ip> : 0x00<isp_mark><tc_class_marks> }
nft insert rule inet nat NAT_PRE \
    ip daddr <public_facing_isp_ip> \
    dnat to <client_ip>
nft insert rule inet filter FILTER_FORWARD ip daddr <client_ip> <action>


#Selective Port Forwarding from a specific source ip

nft add element inet filter allowed_ip4 { <client_ip> }
nft add rule inet mangle prerouting \
    ip saddr <client_ip> <protocol> sport <client_port> \
    meta mark set 0x00<isp_mark><tc_class_marks>
nft add rule inet mangle forward \
    ip daddr <client_ip> <protocol> dport <client_port> \
    meta mark set 0x00<isp_mark><tc_class_marks>
nft insert rule inet nat NAT_PRE \
    ip saddr <public_remote_ip> ip daddr <public_facing_isp_ip> \
    <protocol> dport <public_facing_isp_port> \
    dnat to <client_ip>:<client_port>
nft insert rule inet filter FILTER_FORWARD ip saddr <public_remote_ip> ip daddr <client_ip> <action>

#Selective Port Pool Forwarding with selective remote ip

nft add element inet filter allowed_ip4 { <client_ip> }
nft add rule inet mangle prerouting \
    ip saddr <client_ip> <protocol> sport <starting_client_port>-<ending_client_port> \
    meta mark set 0x00<isp_mark><tc_class_marks>
nft add rule inet mangle forward \
    ip daddr <client_ip> <protocol> dport <starting_client_port>-<ending_client_port> \
    meta mark set 0x00<isp_mark><tc_class_marks>
nft insert rule inet nat NAT_PRE \
    ip saddr <public_remote_ip> ip daddr <public_facing_isp_ip> <protocol> \
    dport <starting_public_facing_isp_port>-<ending_public_facing_isp_port> \
    dnat to <client_ip>:<starting_client_port>-<ending_client_port>
nft insert rule inet filter FILTER_FORWARD ip saddr <public_remote_ip> ip daddr <client_ip> <action>

#Full DMZ All Incoming Traffic → Single Host Specific remote ip

nft add element inet filter allowed_ip4 { <client_ip> }
nft add element inet mangle user4_marks { <client_ip> : 0x00<isp_id><tc_class_id> }
nft insert rule inet nat NAT_PRE ip saddr <public_remote_ip> ip daddr <public_facing_isp_ip> dnat to <client_ip>
nft insert rule inet filter FILTER_FORWARD ip daddr <client_ip> accept