###---To be ran upon wan network interface configuration---###

>These interfaces or interface will be the ones connecting your server to the world wide web.
    # Adds your physical Internet-facing interfaces (e.g., eth0, ppp0) to the 'filter' table's WAN list.
    # This allows the 'Forward' chain to identify which traffic is heading out to the web.

        nft add element inet filter wan_ifaces { "<wan_iface>", "<wan_iface>" }

    # Adds the same interfaces to the 'nat' table.
    # This is crucial for the 'Masquerade' (SNAT) rule so the router knows which exit port 
    # needs its IP address "hidden" before hitting the public internet.

        nft add element inet nat wan_ifaces { "<wan_iface>", "<wan_iface>" }

    # Adds the interfaces to the 'geo' table.
    # This ensures the Geofence only drops incoming traffic from blocked countries if it 
    # arrives on these specific WAN ports, preventing accidental blocking of internal LAN traffic.

        nft add element inet geo wan_ifaces { "<wan_iface>", "<wan_iface>" }
    

###---To be ran upon lan network interface configuration---###

>The lan interfaces will be the interfaces you gave private static ips or are hosting the lan-dhcp off of.
    # Register your local network interfaces in the 'filter' table. 
    # This tells the firewall which 'doors' lead to your private office/home network 
    # so it can apply the Forwarding 'Security Checkpoint' rules.

        nft add element inet filter lan_ifaces { "<lan_iface >", "<lan_iface>" }

    # Register the same interfaces in the 'nat' table. 
    # This is used by the Captive Portal logic to identify which users should be 
    # intercepted and redirected to the login/splash page.

        nft add element inet nat lan_ifaces { "<lan_iface>", "<lan_iface>" }

    # Register the interfaces in the 'webfilter' table. 
    # This ensures that only web traffic coming FROM your internal network is 
    # sent to the NFQUEUE inspection engine, preventing loops or external interference.

    
        nft add element inet webfilter lan_ifaces { "<lan_iface>", "<lan_iface>" }