#Case1: Full Access
##Inserting the rules for setting guideline for bidirectional communication in filter forward for NGFW Rule
nft insert rule inet filter forward ip daddr <local_ip> <action>
nft insert rule inet filter forward ip saddr <local_ip> <action>
##Inserting the rules for setting guideline for bidirectional communication in nat prerouting for NGFW Rule
nft insert rule inet nat prerouting ip daddr <local_ip> <action>
nft insert rule inet nat prerouting ip saddr <local_ip> <action>
## Adding the mark of user and masquerading their traffic 
nft add element inet mangle user4_marks { <local_ip> : 0x00<isp_mark><tc_class_marks> }
nft insert rule inet nat postrouting oifname @wan_ifaces ip saddr <local_ip> masquerade

#Case2: Port / Protocol / Destination-Controlled Access
##Inserting the rules for setting guideline for bidirectional communication in filter forward for NGFW Rule
nft insert rule inet filter forward ip daddr <local_ip> ip saddr <destination_ip> <protocol> dport <destination_port> <action>
nft insert rule inet filter forward ip saddr <local_ip> ip daddr <destination_ip> <protocol> sport <local_port> <action>
##Inserting the rules for setting guideline for bidirectional communication in nat prerouting for NGFW Rule
nft insert rule inet nat prerouting ip daddr <local_ip> ip saddr <destination_ip> <protocol> dport <destination_port> <action>
nft insert rule inet nat prerouting ip saddr <local_ip> ip daddr <destination_ip> <protocol> sport <local_port> <action>
## Adding the mark of user and masquerading their traffic 
nft insert rule inet nat postrouting oifname @wan_ifaces ip saddr <local_ip> ip daddr <destination_ip> <protocol> sport <local_port> masquerade
nft add element inet mangle user4_marks { <local_ip> : 0x00<isp_mark><tc_class_marks> }

#Case3: Destination-IP–Only Managed Access
##Inserting the rules for setting guideline for bidirectional communication in filter forward for NGFW Rule
nft insert rule inet filter forward ip daddr <local_ip> ip saddr <destination_ip> <action>
nft insert rule inet filter forward ip saddr <local_ip> ip daddr <destination_ip> <action>
##Inserting the rules for setting guideline for bidirectional communication in nat prerouting for NGFW Rule
nft insert rule inet nat prerouting ip saddr <local_ip> ip daddr <destination_ip> <action>
nft insert rule inet nat prerouting ip daddr <local_ip> ip saddr <destination_ip> <action>
## Adding the mark of user and masquerading their traffic 
nft insert rule inet nat postrouting oifname @wan_ifaces ip saddr <local_ip> ip daddr <destination_ip> masquerade
nft add element inet mangle user4_marks { <local_ip> : 0x00<isp_mark><tc_class_marks> }
