#main table setup

    # 1. CLEARS THE MAIN ROUTING TABLE: Use with extreme caution. 
    # This removes all routes from the default table, essentially disconnecting the router
    # until the next line is ran.
            ip route flush table main
    
    # 2. RESTORES LOCAL CONNECTIVITY(add all available iface ips and subnets): 
    # Tells the router how to talk to the immediate neighbors on its physical cable.
    # 'src' ensures that packets leaving the router use the correct IP assigned to that interface.
            ip route add <ip_subnet_of_the_ip_on_iface> dev <iface_name> src <ip_on_iface>

#ip rule setup

    # 1. CLEANUP: Deletes any old rules using this specific ISP mark to prevent duplicates.
        ip rule del fwmark 0x00<isp_mark>0000/0x00ff0000 table <table_number>

    # 2. THE STEERING WHEEL:
    # This looks at the packet mark (set earlier in 'mangle').
    # The mask /0x00ff0000 tells the kernel: "Only look at the ISP part of the mark."
    # If the ISP mark matches, the packet is forced to use <table_number>.
        ip rule add fwmark 0x00<isp_mark>0000/0x00ff0000 table <table_number>

#isp table setup

    # 1. TABLE CLEAR: Wipes the specific custom table to ensure no stale routes exist.
        ip route flush table <table_number>

    # 2. THE EXIT: Defines the default gateway for this specific ISP.
    # Any packet landing in this table will be sent to the ISP's router (<gateway_ip>).
        ip route add default via <gateway_ip> dev <iface_name> table <table_number>

    # 3. DIRECT CONNECT(add all available iface ips and subnets): Ensures the table knows that the ISP's local network 
    # is directly reachable on the interface without going through the gateway.
        ip route add <ip_subnet_of_the_ip_on_iface> dev <iface_name> src <ip_on_iface> table <table_number>


        