###---To be ran upon user login---###


    #IPv4 BASED USERS
    # Grants the IP permission to pass through the FORWARD chain (Internet Access).

        nft add element inet filter allowed_ip4 { <client_ip> }

    # Tells the NAT table to stop redirecting this IP to the Login/Splash page.

        nft add element inet nat allowed_ip4 { <client_ip> }

    # Tags the user's traffic with a hex ID. 
    # 0x00[ISP][CLASS] allows the system to apply specific ISP routing and Speed Limits (QoS).

        nft add element inet mangle user4_marks { <client_ip> : 0x00<isp_mark><tc_class_marks> }

    # Adds the IP to the Web Inspection list so their HTTP/HTTPS traffic is sent to the filter engine.

        nft add element inet webfilter ALLOW_ACCESS { <client_ip> }


    #MAC BASED USERS
    # Whitelists the hardware itself. The device can change IPs and still have access.

        nft add element inet filter allowed_macs { <client_mac> }

    # Note: Usually, this should point to 'allowed_macs' in the NAT table to skip the portal.

        nft add element inet nat allowed_macs { <client_mac> }

    # Applies the Speed Limit/Routing mark based on the hardware ID rather than the IP.

        nft add element inet mangle user_mac_marks { <client_mac> : 0x00<isp_mark><tc_class_marks> }

    # Web filtering still requires an IP (since it's Layer 3/4). This enables inspection for the current IP.

        nft add element inet webfilter ALLOW_ACCESS { <client_ip> }


    #IPv4-MAC BASED USERS
    # The 'Security Bond': Traffic is ONLY allowed if <IP> is coming from <MAC>. 
    # This prevents users from stealing a whitelisted IP.

        nft add element inet filter allowed_ip4_mac { <client_ip> . <mac_address> : accept }

    # Tells the NAT table that this specific Pair is authorized to bypass the Captive Portal.

        nft add element inet nat allowed_ip4_mac { <client_ip> . <mac_address> : accept }

    # Maps the IP to the specific Traffic Control (TC) mark for bandwidth management.

        nft add element inet mangle user4_marks { <client_ip> : 0x00<isp_mark><tc_class_marks> }

    # Activates the web content filter for this specific user's IP.

        nft add element inet webfilter ALLOW_ACCESS { <client_ip> }