## CASE 4 (FULL ACCESS, CAPTIVE PORTAL: NO)

nft add set inet filter vpn_<user_ip_set_name> '{ type ipv4_addr; flags interval; }'
nft add element inet filter vpn_<user_ip_set_name> { <vpn_user_ip> }

nft add chain inet filter VPN_<VPN_POLICY_NAME>
nft add rule inet filter VPN_<VPN_POLICY_NAME> ip saddr @vpn_<user_ip_set_name> accept
nft add rule inet filter VPN_<VPN_POLICY_NAME> return

nft insert rule inet filter forward ip saddr @vpn_<user_ip_set_name> jump VPN_<VPN_POLICY_NAME>


## CASE 5 (RESTRICTED ACCESS: SPECIFIC IP + PORT, CAPTIVE PORTAL: NO)

nft add set inet filter vpn_<user_ip_set_name> '{ type ipv4_addr; flags interval; }'
nft add set inet filter vpn_<service_map_name> '{ type ipv4_addr . inet_service; flags interval; }'

nft add chain inet filter VPN_<VPN_POLICY_NAME>
nft add rule inet filter VPN_<VPN_POLICY_NAME> ip saddr @vpn_<user_ip_set_name> ip daddr . tcp dport @vpn_<service_map_name> accept
nft add rule inet filter VPN_<VPN_POLICY_NAME> ip daddr @vpn_<user_ip_set_name> ip saddr . tcp sport @vpn_<service_map_name> accept
nft add rule inet filter VPN_<VPN_POLICY_NAME> return

nft insert rule inet filter forward ip saddr @vpn_<user_ip_set_name> jump VPN_<VPN_POLICY_NAME>

nft add element inet filter vpn_<user_ip_set_name> { <vpn_user_ip> }
nft add element inet filter vpn_<service_map_name> { <destination_ip> . <selected_port> }


## CASE 6 (SEMI-RESTRICTED: IP-ONLY, CAPTIVE PORTAL: YES)

nft add set inet filter vpn_<user_ip_set_name> '{ type ipv4_addr; flags interval; }'
nft add set inet filter vpn_<allowed_ip_set_name> '{ type ipv4_addr; flags interval; }'
nft add set inet nat vpn_<user_ip_set_name> '{ type ipv4_addr; flags interval; }'

nft add chain inet filter VPN_<VPN_POLICY_NAME>
nft add rule inet filter VPN_<VPN_POLICY_NAME> ip saddr @vpn_<user_ip_set_name> ip daddr @vpn_<allowed_ip_set_name> accept
nft add rule inet filter VPN_<VPN_POLICY_NAME> ip daddr @vpn_<user_ip_set_name> ip saddr @vpn_<allowed_ip_set_name> accept
nft add rule inet filter VPN_<VPN_POLICY_NAME> return

nft insert rule inet filter forward ip saddr @vpn_<user_ip_set_name> jump VPN_<VPN_POLICY_NAME>

nft insert rule inet nat prerouting ip saddr @vpn_<user_ip_set_name> tcp dport 80 redirect to :80

nft add element inet filter vpn_<user_ip_set_name> { <vpn_user_ip> }
nft add element inet filter vpn_<allowed_ip_set_name> { <destination_ip> }
nft add element inet nat vpn_<user_ip_set_name> { <vpn_user_ip> }