    # Handling OUTBOUND traffic from the VPN user.
    # 'insert rule': Places this at the TOP of the chain to ensure it bypasses later 'drop' rules.
    # iifname <vpn_iface>: Traffic coming FROM the VPN tunnel.
    # <action>: Usually 'accept' to let VPN users reach the LAN or Internet.

        nft add rule inet filter forward iifname <vpn_iface> <action>

    # Handling INBOUND traffic back to the VPN user.
    # oifname <vpn_iface>: Traffic leaving the router GOING TO the VPN tunnel.
    # This ensures that data requested by the VPN user can actually be sent back to them.

        nft add rule inet filter forward oifname <vpn_iface> <action>